name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy Gym
        uses: actions/checkout@v4
        with:
          path: gym
          persist-credentials: false
      
      - name: Run Tests
        run: |
          cd gym
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          docker run --rm -v `pwd`:/gym unifyai/gym:latest python3 -m pytest ivy_gym_tests/
